### PR TITLE
Added voice support for Covid cases

### PR DESCRIPTION
**Pull request by Kishore-abhimanyu**

### CODE REVIEW

**Comment by Kishore-abhimanyu** [comment]
Please revire the PR and merge it or post relevant messages

**Review by rohitjoshi6 — CHANGES_REQUESTED** [review]
@Kishore-abhimanyu Can you add your function call for covid cases in the if-elif ladder
image

Call the function only when the user wants to know about the covid cases

**Comment by Kishore-abhimanyu** [comment]
Can you check now?

**Review by rohitjoshi6 — APPROVED** [review]

**Review by rohitjoshi6 — CHANGES_REQUESTED** [review]
There are still some merge conflicts due to which I am unable to merge your PR

**Comment by Kishore-abhimanyu** [comment]
can you merge now?

**Review by rohitjoshi6 — APPROVED** [review]

**Comment by rohitjoshi6** [comment]
Good work @Kishore-abhimanyu 
Thanks for contributing

**Pull request merged**
