### PR TITLE
What can you do

### LINKED ISSUE #92: What can you do
If the user asks what can assistant do for me then the assistant should replay all his features such as 
"I can open application, close application, suggest you a movie, play music, taking photos and all"

### PR DESCRIPTION
**Pull request by BAHETIHARSH**
#92 assistant will tell the user all the abilities it possesses

### CODE REVIEW

**Comment by rohitjoshi6** [comment]
Pull all the changes from upstream @BAHETIHARSH

**Comment by BAHETIHARSH** [comment]
Done

**Comment by rohitjoshi6** [comment]
Is there a reason for using speak() 4 times?
image

**Comment by BAHETIHARSH** [comment]
it will give a small pause.

**Review by rohitjoshi6 — APPROVED** [review]

**Comment by rohitjoshi6** [comment]
I am merging this PR but you can specify the pause time too [ sleep() ].
Good work & thank you for contributing

**Pull request merged**
