### PR TITLE
Added joke functionality

### LINKED ISSUE #6: Tell jokes to user
### Example:

User: Hey, tell me a joke
FRIDAY(Voice assistant) : {Insert a joke here}

### PR DESCRIPTION
**Pull request by Pranjalmishra30**
Fixes #6 
FRIDAY now tells a joke. Jokes fetched from this [api](https://icanhazdadjoke.com/api)

### CODE REVIEW

**Review by rohitjoshi6 — CHANGES_REQUESTED** [review]
@Pranjalmishra30 can you add your function call within the if-elif ladder..
image
Just change the "if" to "elif"

**Comment by Pranjalmishra30** [comment]
Updated with the requested change

**Comment by rohitjoshi6** [comment]
@Pranjalmishra30 Can you please pull all the changes from upstream  because there are some merge conflicts with your PR

**Comment by Pranjalmishra30** [comment]
@rohitjoshi6 Please have a look, i think all conflcts are resolved. Do let me know if i need to do anything else

**Review by rohitjoshi6 — APPROVED** [review]

**Comment by rohitjoshi6** [comment]
Thank you @Pranjalmishra30 for the contribution

**Pull request merged**
